In [48]:
import json
import pandas as pd
from citipy import citipy
from random import randint
from datetime import datetime

In [49]:
import matplotlib.pyplot as plt
import requests as req
import time

In [50]:
# something = [('blue', 'red'), ('purple', 'green')]
# something2 = ('purple', 'green')
# if something2 not in something:
#     something.append(something2)
# print(something)
# print(len(something))
# some = ('bleep', 'bloop')

In [51]:
combined_list = []

while len(combined_list) < 20:
    lat_range = randint(-90,90)
    lng_range = randint(-180, 180)
    city = citipy.nearest_city(lat_range, lng_range)
    city_name = city.city_name
    country_name = city.country_code
    combined_ = (city_name, country_name) #'combined' is a tuple, used to compare BOTH city,country (in case of same city names, but different countries)
    if combined_ not in combined_list:
        combined_list.append(combined_)

In [52]:
# combined_dict = {}

# while len(combined_dict) < 10:
#     lat_range = randint(-90,90)
#     lng_range = randint(-180, 180)
#     city = citipy.nearest_city(lat_range, lng_range)
#     city_name = city.city_name
#     country_name = city.country_code
#     #key, value = city_name, country_name
#     if (city_name not in combined_dict.keys()) or (combined_dict[city_name] == country_name):
#         combined_dict[city_name] = country_name

# print(combined_dict)

In [53]:
city_list, country_list = zip(*combined_list)
city_list = list(city_list)
country_list = list(country_list)
print(city_list)
print(country_list)

['ushuaia', 'kalanwali', 'tuatapere', 'castro', 'mys shmidta', 'kahului', 'coruripe', 'sosnogorsk', 'belushya guba', 'shush', 'san narciso', 'umzimvubu', 'caravelas', 'airai', 'rikitea', 'vaitupu', 'fereydunshahr', 'hirara', 'barentsburg', 'synya']
['ar', 'in', 'nz', 'cl', 'ru', 'us', 'br', 'ru', 'ru', 'ir', 'ph', 'za', 'br', 'pw', 'pf', 'wf', 'ir', 'jp', 'sj', 'ru']

In [55]:
url = "http://api.openweathermap.org/data/2.5/weather"
api_key = "520a1531cd2ce1c453e489ffd47eb034"

time_str1 = "Jul 27 01:50:06 +0000 2017"

converted_time1 = datetime.strptime(time_str1,
                                    "%b %d %H:%M:%S %z %Y")

start_unixtime = str(int(time.mktime(converted_time1.timetuple())))

lat_data = []
temp_data = []
humid_data = []
cloud_data = []
wind_data = []
number = 1
for each_city, each_country in combined_list:
    print("Collecting data on city #" + str(number) + ': ' + str(each_city) + ', ' + str(each_country))
    try:
        params = {'appid': api_key,
                  'q': each_city + ',' + each_country,
                  'type': 'hour',
                  'start': start_unixtime,
                  'cnt': 1}
    
        weather_response = req.get(url, params)
        print("Requested URL: " + str(weather_response.url))
        weather_json = weather_response.json()
        lat_data.append(weather_json['coord']['lat'])
        temp_data.append(weather_json['main']['temp'])
        humid_data.append(weather_json['main']['humidity'])
        cloud_data.append(weather_json['clouds']['all'])
        wind_data.append(weather_json['wind']['speed'])
    except:
        print("Some part of the combined_list data is missing, appending NaN")
        lat_data.append('NaN')
        temp_data.append('NaN')
        humid_data.append('NaN')
        cloud_data.append('NaN')
        wind_data.append('NaN')
    number += 1
    
#print(json.dumps(weather_json, indent=4, sort_keys=True))
print(lat_data)
print(temp_data)
print(humid_data)
print(cloud_data)
print(wind_data)

Collecting data on city #1: ushuaia, ar
Requested URL: http://api.openweathermap.org/data/2.5/weather?appid=520a1531cd2ce1c453e489ffd47eb034&q=ushuaia%2Car&type=hour&start=1501145406&cnt=1
Collecting data on city #2: kalanwali, in
Requested URL: http://api.openweathermap.org/data/2.5/weather?appid=520a1531cd2ce1c453e489ffd47eb034&q=kalanwali%2Cin&type=hour&start=1501145406&cnt=1
Collecting data on city #3: tuatapere, nz
Requested URL: http://api.openweathermap.org/data/2.5/weather?appid=520a1531cd2ce1c453e489ffd47eb034&q=tuatapere%2Cnz&type=hour&start=1501145406&cnt=1
Collecting data on city #4: castro, cl
Requested URL: http://api.openweathermap.org/data/2.5/weather?appid=520a1531cd2ce1c453e489ffd47eb034&q=castro%2Ccl&type=hour&start=1501145406&cnt=1
Collecting data on city #5: mys shmidta, ru
Requested URL: http://api.openweathermap.org/data/2.5/weather?appid=520a1531cd2ce1c453e489ffd47eb034&q=mys+shmidta%2Cru&type=hour&start=1501145406&cnt=1
Some part of the combined_list data is missing
Collecting data on city #6: kahului, us
Requested URL: http://api.openweathermap.org/data/2.5/weather?appid=520a1531cd2ce1c453e489ffd47eb034&q=kahului%2Cus&type=hour&start=1501145406&cnt=1
Collecting data on city #7: coruripe, br
Requested URL: http://api.openweathermap.org/data/2.5/weather?appid=520a1531cd2ce1c453e489ffd47eb034&q=coruripe%2Cbr&type=hour&start=1501145406&cnt=1
Collecting data on city #8: sosnogorsk, ru
Requested URL: http://api.openweathermap.org/data/2.5/weather?appid=520a1531cd2ce1c453e489ffd47eb034&q=sosnogorsk%2Cru&type=hour&start=1501145406&cnt=1
Collecting data on city #9: belushya guba, ru
Requested URL: http://api.openweathermap.org/data/2.5/weather?appid=520a1531cd2ce1c453e489ffd47eb034&q=belushya+guba%2Cru&type=hour&start=1501145406&cnt=1
Some part of the combined_list data is missing
Collecting data on city #10: shush, ir
Requested URL: http://api.openweathermap.org/data/2.5/weather?appid=520a1531cd2ce1c453e489ffd47eb034&q=shush%2Cir&type=hour&start=1501145406&cnt=1
Collecting data on city #11: san narciso, ph
Requested URL: http://api.openweathermap.org/data/2.5/weather?appid=520a1531cd2ce1c453e489ffd47eb034&q=san+narciso%2Cph&type=hour&start=1501145406&cnt=1
Collecting data on city #12: umzimvubu, za
Requested URL: http://api.openweathermap.org/data/2.5/weather?appid=520a1531cd2ce1c453e489ffd47eb034&q=umzimvubu%2Cza&type=hour&start=1501145406&cnt=1
Some part of the combined_list data is missing
Collecting data on city #13: caravelas, br
Requested URL: http://api.openweathermap.org/data/2.5/weather?appid=520a1531cd2ce1c453e489ffd47eb034&q=caravelas%2Cbr&type=hour&start=1501145406&cnt=1
Collecting data on city #14: airai, pw
Requested URL: http://api.openweathermap.org/data/2.5/weather?appid=520a1531cd2ce1c453e489ffd47eb034&q=airai%2Cpw&type=hour&start=1501145406&cnt=1
Some part of the combined_list data is missing
Collecting data on city #15: rikitea, pf
Requested URL: http://api.openweathermap.org/data/2.5/weather?appid=520a1531cd2ce1c453e489ffd47eb034&q=rikitea%2Cpf&type=hour&start=1501145406&cnt=1
Collecting data on city #16: vaitupu, wf
Requested URL: http://api.openweathermap.org/data/2.5/weather?appid=520a1531cd2ce1c453e489ffd47eb034&q=vaitupu%2Cwf&type=hour&start=1501145406&cnt=1
Some part of the combined_list data is missing
Collecting data on city #17: fereydunshahr, ir
Requested URL: http://api.openweathermap.org/data/2.5/weather?appid=520a1531cd2ce1c453e489ffd47eb034&q=fereydunshahr%2Cir&type=hour&start=1501145406&cnt=1
Collecting data on city #18: hirara, jp
Requested URL: http://api.openweathermap.org/data/2.5/weather?appid=520a1531cd2ce1c453e489ffd47eb034&q=hirara%2Cjp&type=hour&start=1501145406&cnt=1
Collecting data on city #19: barentsburg, sj
Requested URL: http://api.openweathermap.org/data/2.5/weather?appid=520a1531cd2ce1c453e489ffd47eb034&q=barentsburg%2Csj&type=hour&start=1501145406&cnt=1
Some part of the combined_list data is missing
Collecting data on city #20: synya, ru
Requested URL: http://api.openweathermap.org/data/2.5/weather?appid=520a1531cd2ce1c453e489ffd47eb034&q=synya%2Cru&type=hour&start=1501145406&cnt=1
[-54.8, 29.85, -46.13, -42.47, 'NaN', 20.89, -10.13, 63.6, 'NaN', 32.19, 15.01, 'NaN', -17.71, 'NaN', -23.12, 'NaN', 32.94, 24.8, 'NaN', 65.37]
[278.15, 294.666, 290.316, 280.991, 'NaN', 296.03, 298.641, 267.341, 'NaN', 291.591, 304.15, 'NaN', 298.191, 'NaN', 297.916, 'NaN', 281.441, 293.66, 'NaN', 266.891]
[75, 84, 73, 98, 'NaN', 83, 99, 75, 'NaN', 59, 58, 'NaN', 100, 'NaN', 100, 'NaN', 24, 94, 'NaN', 82]
[0, 0, 0, 0, 'NaN', 40, 92, 76, 'NaN', 8, 75, 'NaN', 68, 'NaN', 92, 'NaN', 0, 75, 'NaN', 88]
[2.6, 2.03, 5.05, 3.63, 'NaN', 4.1, 7.65, 3.15, 'NaN', 1.6, 2.6, 'NaN', 7.08, 'NaN', 6.18, 'NaN', 1.38, 10.3, 'NaN', 4.53]

In [56]:
weather_dict = {"Latitude": lat_data, "City": city_list, "Country": country_list, "Temperature": temp_data, "Humidity": humid_data, "Cloudiness": cloud_data, "Wind Speed": wind_data}
print(weather_dict)

{'Latitude': [-54.8, 29.85, -46.13, -42.47, 'NaN', 20.89, -10.13, 63.6, 'NaN', 32.19, 15.01, 'NaN', -17.71, 'NaN', -23.12, 'NaN', 32.94, 24.8, 'NaN', 65.37], 'City': ['ushuaia', 'kalanwali', 'tuatapere', 'castro', 'mys shmidta', 'kahului', 'coruripe', 'sosnogorsk', 'belushya guba', 'shush', 'san narciso', 'umzimvubu', 'caravelas', 'airai', 'rikitea', 'vaitupu', 'fereydunshahr', 'hirara', 'barentsburg', 'synya'], 'Country': ['ar', 'in', 'nz', 'cl', 'ru', 'us', 'br', 'ru', 'ru', 'ir', 'ph', 'za', 'br', 'pw', 'pf', 'wf', 'ir', 'jp', 'sj', 'ru'], 'Temperature': [278.15, 294.666, 290.316, 280.991, 'NaN', 296.03, 298.641, 267.341, 'NaN', 291.591, 304.15, 'NaN', 298.191, 'NaN', 297.916, 'NaN', 281.441, 293.66, 'NaN', 266.891], 'Humidity': [75, 84, 73, 98, 'NaN', 83, 99, 75, 'NaN', 59, 58, 'NaN', 100, 'NaN', 100, 'NaN', 24, 94, 'NaN', 82], 'Cloudiness': [0, 0, 0, 0, 'NaN', 40, 92, 76, 'NaN', 8, 75, 'NaN', 68, 'NaN', 92, 'NaN', 0, 75, 'NaN', 88], 'Wind Speed': [2.6, 2.03, 5.05, 3.63, 'NaN', 4.1, 7.65, 3.15, 'NaN', 1.6, 2.6, 'NaN', 7.08, 'NaN', 6.18, 'NaN', 1.38, 10.3, 'NaN', 4.53]}

In [57]:
weather_df = pd.DataFrame(weather_dict)
weather_df

             City Cloudiness Country Humidity Latitude Temperature Wind Speed
0         ushuaia          0      ar       75    -54.8      278.15        2.6
1       kalanwali          0      in       84    29.85     294.666       2.03
2       tuatapere          0      nz       73   -46.13     290.316       5.05
3          castro          0      cl       98   -42.47     280.991       3.63
4     mys shmidta        NaN      ru      NaN      NaN         NaN        NaN
5         kahului         40      us       83    20.89      296.03        4.1
6        coruripe         92      br       99   -10.13     298.641       7.65
7      sosnogorsk         76      ru       75     63.6     267.341       3.15
8   belushya guba        NaN      ru      NaN      NaN         NaN        NaN
9           shush          8      ir       59    32.19     291.591        1.6
10    san narciso         75      ph       58    15.01      304.15        2.6
11      umzimvubu        NaN      za      NaN      NaN         NaN        NaN
12      caravelas         68      br      100   -17.71     298.191       7.08
13          airai        NaN      pw      NaN      NaN         NaN        NaN
14        rikitea         92      pf      100   -23.12     297.916       6.18
15        vaitupu        NaN      wf      NaN      NaN         NaN        NaN
16  fereydunshahr          0      ir       24    32.94     281.441       1.38
17         hirara         75      jp       94     24.8      293.66       10.3
18    barentsburg        NaN      sj      NaN      NaN         NaN        NaN
19          synya         88      ru       82    65.37     266.891       4.53